# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem 'solargraph', '0.44.3'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'rubocop', '1.27.0', require: false
  gem 'rubocop-performance', '1.13.3', require: false
  gem 'rubocop-rails', '2.14.2', require: false
  gem 'rubocop-rspec', '2.10.0', require: false
end
